Spring cleaning (#34)
* Update dependencies, adjust `devDependencies`

Many dev dependencies were included as prod, so those have been moved to
dev in preparation for the updated compilation/build workflow.

* Properly connect default NNG sockets

Previous implementation was not working, so now `os.homedir()` is called
if command line arguments are missing.

* Final change to Prisma generator output

I finally figured it out! :)

* `database.ts`: JSDoc, minor adjustments

* Adjustments to `processTransactionOutputs()`

Update wording on some comments, rename constants for better readability,
and adjust some logic/formatting.

* `api.ts`: rename `Parameter` types, improve logging

* `constants.ts`: add `node:os` import

This should have been included in f973204

* Remove `.npmrc`

It was only omitting dev dependencies by default, and it was causing
more trouble than was necessary. Dev dependencies are now easily removed
with `npm run 'build:prod'`

* Move `npm start` script to `./index.ts`

* Add `dotenv-cli` package

This will be used in `npm start` to load `DATABASE_URL` environment
variable at runtime, rather than Prisma trying to load it. If we use
`rank-backend-ts` as a submodule in another package, Prisma will have
trouble reading its local `.env` file. `dotenv-cli` will work around this
issue.

* Adjust package main/startup script, add build scripts

* Load `DATABASE_URL` on `npm start`, use env in `PrismaClient`

This commit runs `dotenv -e ./.env` to load the necessary `DATABASE_URL`
variable into the environment, and sets the `PrismaClient` to read this
variable when instantiated.

* Consolidate and adjust `tsconfig.json`

* Update `.gitignore`

* Add submodule paths to `tsconfig.json`

Fixes this runtime error:
```
Error: Cannot find module '/app/node_modules/rank-lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:487:19)
    at Module._findPath (node:internal/modules/cjs/loader:771:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1211:27)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/app/.output/lib/indexer.js:41:20)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/app/node_modules/rank-lib/package.json',
  requestPath: 'rank-lib'
```

* More `tsconfig.json` adjustments

* Add `ts-patch`, `typescript-transform-paths` packages

* Remove 'baseUrl' from 'tsconfig.json'

This was causing the path to `rank-lib` to be transformed based on the
source directory rather than the `.output` directory.

* Set `rootDirs` for proper custom path resolution

ref: https://github.com/LeDDGroup/typescript-transform-paths?tab=readme-ov-file#virtual-directories

* `schema.prisma`: Formatting and index changes

* Pick from `RankTarget` for `RankStatistics` type

* Update `.gitignore` again

* Update `LICENSE`